const products = [{
    id: 1,
    accessory: "Sea life",
    background: "Moon and birds",
    expression: "Brown eyes",
    hairstyle: "Long and straight",
    name: "Miya",
    outfit: "Winter",
    prop: null,
    price: 9.1347,
}, {
    id: 2,
    accessory: null,
    background: "Night & sky",
    expression: "Brown eyes",
    hairstyle: "Double ponies",
    name: "Rina",
    outfit: "Astronaut",
    prop: null,
    price: 9.1347,
}, {
    id: 3,
    accessory: null,
    background: "Sun & mucha",
    expression: "Brown eyes",
    hairstyle: "Pixie",
    name: "Aubreeanna",
    outfit: "Steampunk",
    prop: "Skateboard",
    price: 9.1347,
}, {
    id: 4,
    accessory: null,
    background: "Amai",
    expression: "Gaze right",
    hairstyle: "Short bob",
    name: "Aubreeanna",
    outfit: "Steampunk",
    prop: "Skateboard",
    price: 8.6001,
}, {
    id: 5,
    accessory: null,
    background: "Casino",
    expression: "Gaze close",
    hairstyle: "Short bob",
    name: "Yeeun",
    outfit: "Steampunk",
    prop: "Cell phone",
    price: 8.6001,
}, {
    id: 6,
    accessory: "Headphones",
    background: "Sun & mucha",
    expression: "Brown eyes",
    hairstyle: "Ponytail",
    name: "Kotoko",
    outfit: "Kotoko",
    prop: "Skateboard",
    price: 9.1348,
}, {
    id: 7,
    accessory: null,
    background: "Sun & mucha",
    expression: "Brown eyes",
    hairstyle: "Double ponies",
    name: "Sinead",
    outfit: "Steampunk",
    prop: "Lolipop",
    price: 9.1348,
}, {
    id: 8,
    accessory: null,
    background: "Night & sky",
    expression: "Brown eyes",
    hairstyle: "Bangs & buns",
    name: "Ataya",
    outfit: "French maid",
    prop: "Teddy bear",
    price: 9.1348,
}, {
    id: 9,
    accessory: null,
    background: "Neonpunk",
    expression: "Gaze star",
    hairstyle: "Double ponies",
    name: "JiaYi",
    outfit: "Kimono",
    prop: "Mic",
    prop2: "Cellphone",
    price: 8.6001,
}, {
    id: 10,
    accessory: null,
    background: "Night & sky",
    expression: "Brown eyes",
    hairstyle: "Double ponies",
    name: "ZhiLei",
    outfit: "Hip hop",
    prop: "Skateboard",
    price: 9.1348,
}, {
    id: 11,
    accessory: "Pet shop",
    background: "Steampunk",
    expression: "Brown eyes",
    hairstyle: "Short bob",
    name: "Mayo",
    outfit: "Steampunk",
    prop: null,
    price: 9.1345,
}, {
    id: 12,
    accessory: null,
    background: "Casino",
    expression: "Gaze close",
    hairstyle: "Europop",
    name: "Candice",
    outfit: "Summer",
    prop: "Mic",
    price: 8.6001,
}, {
    id: 13,
    accessory: null,
    background: "Amai",
    expression: "Brown eyes",
    hairstyle: "Double ponies",
    name: "Paige",
    outfit: "French maid",
    prop: "Skateboard",
    price: 9.1346,
}, {
    id: 14,
    accessory: "Headphones",
    background: "Casino",
    expression: "Brown eyes",
    hairstyle: "Short bob",
    name: "Hyesu",
    outfit: "Summer",
    prop: "Boba tea",
    price: 9.1346,
}, {
    id: 15,
    accessory: null,
    background: "Sun & mucha",
    expression: "Gaze afar",
    hairstyle: "Europop",
    name: "HuiQing",
    outfit: "Qipao",
    prop: null,
    price: 8.6001,
}]